/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_isistan_jni_CLib */

#ifndef _Included_edu_isistan_jni_CLib
#define _Included_edu_isistan_jni_CLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_isistan_jni_CLib
 * Method:    dotMultiplication
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_edu_isistan_jni_CLib_dotMultiplication
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
